### ISSUE TITLE
Alsa Mixer

### ISSUE THREAD

**Issue by grtstha** [supremegamers/darkmatter#6]
I got this error after opening alsa mixer utility from gearlock.
![Screenshot_20210924-132017](https://user-images.githubusercontent.com/85688008/134623516-23c844c5-78c4-483e-bd15-aed90d967fe8.jpg)

**Comment by axonasif** [comment]
Please follow the proper bug report issue template or kindly don't create one, because without the detailed and necessary information we can not help you.

https://github.com/supremegamers/darkmatter/issues/new?assignees=axonasif&labels=bug&template=bug_report.md&title=
![Screenshot_20210924-114226.png](https://user-images.githubusercontent.com/39482679/134624242-4861bd6b-de3c-4221-8c91-3a06e018d139.png)
